#--------------------------------------------------------------#
#                            ~ dev ~                           #
#--------------------------------------------------------------#



command /srvname <text>:
	trigger:
		if player is {dev::%player%} and op:
			if arg 1 isn't set:
				send "&4&l>> &cErreur &4&l<< &e- &6Merci de set un nom pour votre serveur" to player
				stop
			else:
				set {serveur} to arg 1
				send "&a&l>> &dSuccès &a&l<< &e- &6Vous venez de set le nom de votre serveur en %{serveur}%" to player
				if {boutique} and {discord} and {serveur} is set:
					wait 5 second 
					send "&a&l>> &dSuccès &a&l<< &e- &aVous avez finis de configurer votre serveur !" to player
					set {jobs.gratuit.etat.dispo} to 3
					set {jobs.vip.etat.dispo} to 2
					set {jobs.gratuit.etat.indispo} to 0
					set {jobs.vip.etat.indispo} to 0
					set {PrisonRP.visit.draxy} to 0
					stop
				stop
				
command /srvdiscord <text>:
	trigger:
		if player is {dev::%player%} and op:
			if arg 1 isn't set:
				send "&4&l>> &cErreur &4&l<< &e- &6Merci de set les numéros de votre discord &fex: &bHKRnzfQN" to player
				if {boutique} and {discord} and {serveur} is set:
					wait 5 second 
					send "&a&l>> &dSuccès &a&l<< &e- &aVous avez finis de configurer votre serveur !" to player
					set {jobs.gratuit.etat.dispo} to 3
					set {jobs.vip.etat.dispo} to 2
					set {jobs.gratuit.etat.indispo} to 0
					set {jobs.vip.etat.indispo} to 0
					set {PrisonRP.visit.draxy} to 0
					stop
				stop
			else:
				set {discord} to arg 1
				send "&a&l>> &dSuccès &a&l<< &e- &6Vous venez de set votre discord en discord.gg/%{discord}%" to player
				stop	

command /srvboutique <text>:
	trigger:
		if player is {dev::%player%} and op:
			if arg 1 isn't set:
				send "&4&l>> &cErreur &4&l<< &e- &6Merci de set l'url de votre boutique" to player
				if {boutique} and {discord} and {serveur} is set:
					wait 5 second 
					send "&a&l>> &dSuccès &a&l<< &e- &aVous avez finis de configurer votre serveur !" to player
					set {jobs.gratuit.etat.dispo} to 3
					set {jobs.vip.etat.dispo} to 2
					set {jobs.gratuit.etat.indispo} to 0
					set {jobs.vip.etat.indispo} to 0
					set {PrisonRP.visit.draxy} to 0
					stop
				stop
			else:
				set {boutique} to arg 1
				send "&a&l>> &dSuccès &a&l<< &e- &6Vous venez de set votre boutique %{boutique}%" to player
				stop	


				
every 30 seconds:
	if {boutique} or {discord} or {serveur} isn't set:
		send "&4&l>> &cInfo &4&l<< &e- &6Pour terminer la configuration du serveur mettez-vous en tant que opérateur sur le serveur (/op <pseudo>) et ensuite faites /developpeur" to all players
		stop

every 5 minutes:
	if {boutique} or {discord} or {serveur} isn't set:
		send "&4&l>> &cInfo &4&l<< &e- &6Vous pouvez ajouter des membres du staff sans les ajouters opérateurs en faisant (/staffs add <pseudo>) ou les retirers en faisant (/staffs remove <pseudo>)" to {dev::*} and {staffs::*}
		stop


every 2 minutes:
	if {boutique} isn't set:
		send "&4&l>> &cErreur &4&l<< &e- &6Merci de set votre boutique en faisant /srvboutique <nom de votre boutique>" to {dev::*}
		stop

every 2 minutes:
	if {discord} isn't set:
		send "&4&l>> &cErreur &4&l<< &e- &6Merci de set votre discord en faisant /srvdiscord <nom de votre discord>" to {dev::*}
		stop

every 2 minutes:
	if {serveur} isn't set:
		send "&4&l>> &cErreur &4&l<< &e- &6Merci de set un nom pour votre serveur en faisant /srvname <nom de votre serveur>" to {dev::*}
		stop


command /location:
	trigger:
		if player is {dev::%player%} or op:
			set {player.under} to player's location
			send "%{player.under}%" to player
			stop

command /developpeur:
	trigger:
		if player is op:	
			if player is {staff.service::%player%}:	
				send "&4&l>> &cErreur &4&l<< &e- &6Vous ne pouvez pas vous mettre en tant que développeur sur le serveur tant que vous êtes en mode Staff. Faites /staff pour vous retirer du mode Staff !" to player
				stop
			if player is {dev::%player%}:
				if player is in world "world": 
					clear {dev::%player%}	
					clear player's inventory
					set {lobby::%player%} to player
					teleport player to location(-4.514, 67, 29.507, world("lobby"), 2.8, 0.6)
					set current hotbar slot of player to 0
					if player is {staffs::%player%} or op:
						set slot 0 of player to Diamond Axe named "&dMode Staff &7(Clique droit)"					
					set slot 3 of player to Clock named "&aMenu des Jeux %{serveur}% RP &7(Clique droit)"
					set slot 5 of player to gold ingot of sharpness 1 named "&eBoutique &7(Clique droit)"
					if player is op:
						set slot 8 of player to Emerald named "&6Mode développeur &7(Clique droit)"
					send "&e&l>> &4Vous n'êtes plus en mode developpeur !" to player
					remove night vision from the player
					wait 3 seconds
					set player's game mode to survival
					stop
			else:
				if player isn't {dev::%player%}:
					if player is in world "lobby": 
						if {boutique} isn't set:
							send "&4&l>> &cErreur &4&l<< &e- &6Merci de set votre boutique en vous mettant en mode developpeur et faire /srvboutique <nom de votre boutique>" to op
						if {discord} isn't set:
							send "&4&l>> &cErreur &4&l<< &e- &6Merci de set votre discord en vous mettant en mode developpeur et faire /srvdiscord <nom de votre discord>" to op
						if {serveur} isn't set:
							send "&4&l>> &cErreur &4&l<< &e- &6Merci de set un nom pour votre serveur en vous mettant en mode developpeur et faire /srvname <nom de votre serveur>" to op
						clear {lobby::%player%}
						clear player's inventory
						set {dev::%player%} to player
						apply night vision to the player for 100000 seconds
						teleport player to location(-1281.574, 17, 1263.418, world("world"), -90, 1.3)
						wait 1 seconds
						set slot 8 of player to trapped chest named "&e&lParamètres du Serveur &7(Clique droit)"
						send "&e&l>> &aVous êtes en mode developpeur !" to player
						wait 2 seconds
						set player's game mode to creative
						stop
		else:
			send "&e&l>> &cPour vous mettre en mode developpeur vous devez être opérateur et au lobby du serveur !" to player
			stop

#--------------------------------------------------------------#
#                          ~ Debug ~                           #
#--------------------------------------------------------------#

command /debug:
	permission: staff.debug
	trigger:
		set {couvrefeu} to false
		set {couvrefeu.all} to false
		set {prisonnier.nb} to 0
		set {garde.nb} to 0
		set {bri.nb} to 0
		set {staff.nb} to 0
		stop

#--------------------------------------------------------------#
#                   ~ Paramètres du serveur ~                  #
#--------------------------------------------------------------#

on rightclick:
	name of player's held item contains "&e&lParamètres du Serveur"
	cancel event
	if player is {dev::%player%}:	
		wait 3 tick
		open chest inventory with 3 rows named "      &e&lParamètres du Serveur" to player
		make a gui slot 0 of player with Red Stained Glass Pane named "&4Quitter" to close
		make a gui slot 1 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 2 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 3 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 4 of player with Red Stained Glass Pane named "&4Quitter" to close
		make a gui slot 5 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 6 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 7 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 8 of player with Red Stained Glass Pane named "&4Quitter" to close
		make a gui slot 9 of player with White Glass Pane named "&cPrisonRP" to close
		make a gui slot 10 of player with White Glass Pane named "&cPrisonRP" to close
		make a gui slot 11 of player with Bone named "&d&l:| &a&lTrades Parameter &d&l|" to run:
			wait 3 tick
			open chest inventory with 5 rows named "      &a&lTrades Parameter" to player
			make a gui slot 0 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 1 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 2 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 3 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 4 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 5 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 6 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 7 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 8 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 9 of player with White Glass Pane named "&cPrisonRP" to close
			make a gui slot 10 of player with White Glass Pane named "&cPrisonRP" to close
			if {jobs.prisonnier.etat} isn't "false":
				make a gui slot 11 of player with Lime Dye named "&4&l:| &c&lMETIER DE PRISONNIER &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lPrisonnier actuel &f&l-> &a&l%{prisonnier.number}%" and "  " and "&aEtat &f&l> &a&lActif" and "" and "&7Clic gauche pour désactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.prisonnier.etat} to "false"
					remove 1 from {jobs.gratuit.etat.dispo}
					add 1 to {jobs.gratuit.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de Prisonnier a été &d&lDésactivé."
					stop
			else:
				make a gui slot 11 of player with Pink Dye named "&4&l:| &c&lMETIER DE PRISONNIER &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lPrisonnier actuel &f&l-> &a&l%{prisonnier.number}%" and "  " and "&aEtat &f&l> &d&lDesactivé" and "" and "&7Clic gauche pour réactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.prisonnier.etat} to "true"
					add 1 to {jobs.gratuit.etat.dispo}
					remove 1 from {jobs.gratuit.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de Prisonnier a été &d&lRéactivé."
					stop	
			make a gui slot 12 of player with White Stained Glass Pane named "&cPrisonRP" to close
			if {jobs.garde.etat} isn't "false":
				make a gui slot 13 of player with Lime Dye named "&4&l:| &c&lMETIER DE GARDE &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lGarde actuel &f&l-> &a&l%{garde.number}%" and "  " and "&aEtat &f&l> &a&lActif" and "" and "&7Clic gauche pour désactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.garde.etat} to "false"
					remove 1 from {jobs.gratuit.etat.dispo}
					add 1 to {jobs.gratuit.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de Garde a été &d&lDésactivé."
					stop
			else:
				make a gui slot 13 of player with Pink Dye named "&4&l:| &c&lMETIER DE GARDE &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lGarde actuel &f&l-> &a&l%{garde.number}%" and "  " and "&aEtat &f&l> &d&lDesactivé" and "" and "&7Clic gauche pour réactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.garde.etat} to "true"
					add 1 to {jobs.gratuit.etat.dispo}
					remove 1 from {jobs.gratuit.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de Garde a été &d&lRéactivé."
					stop
			make a gui slot 14 of player with White Stained Glass Pane named "&cPrisonRP" to close
			if {jobs.directeur.etat} isn't "false":
				make a gui slot 15 of player with Lime Dye named "&4&l:| &c&lMETIER DE DIRECTEUR &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lDirecteur actuel &f&l-> &a&l%{directeur.number}%" and "  " and "&aEtat &f&l> &a&lActif" and "" and "&7Clic gauche pour désactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.directeur.etat} to "false"
					remove 1 from {jobs.gratuit.etat.dispo}
					add 1 to {jobs.gratuit.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de Directeur a été &d&lDésactivé."
					stop
			else:
				make a gui slot 15 of player with Pink Dye named "&4&l:| &c&lMETIER DE DIRECTEUR &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lDirecteur actuel &f&l-> &a&l%{directeur.number}%" and "  " and "&aEtat &f&l> &d&lDesactivé" and "" and "&7Clic gauche pour réactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.directeur.etat} to "true"
					add 1 to {jobs.gratuit.etat.dispo}
					remove 1 from {jobs.gratuit.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de Directeur a été &d&lRéactivé."
					stop
			make a gui slot 16 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 17 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 18 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 19 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 20 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 21 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 22 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 23 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 24 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 25 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 26 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 27 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 28 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 29 of player with White Stained Glass Pane named "&cPrisonRP" to close
			if {jobs.chefgarde.etat} isn't "false":
				make a gui slot 30 of player with Lime Dye named "&4&l:| &c&lMETIER DE CHEF-GARDE &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lChef-Garde actuel &f&l-> &a&l%{chefgarde.number}%" and "  " and "&aEtat &f&l> &a&lActif" and "" and "&7Clic gauche pour désactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.chefgarde.etat} to "false"
					remove 1 from {jobs.vip.etat.dispo}
					add 1 to {jobs.vip.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de ChefGarde a été &d&lDésactivé."
					stop
			else:
				make a gui slot 30 of player with Pink Dye named "&4&l:| &c&lMETIER DE CHEF-GARDE &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lChef-Garde actuel &f&l-> &a&l%{chefgarde.number}%" and "  " and "&aEtat &f&l> &d&lDesactivé" and "" and "&7Clic gauche pour réactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.chefgarde.etat} to "true"
					add 1 to {jobs.vip.etat.dispo}
					remove 1 from {jobs.vip.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de ChefGarde a été &d&lRéactivé."
					stop
			make a gui slot 31 of player with White Stained Glass Pane named "&cPrisonRP" to close
			if {jobs.bri.etat} isn't "false":
				make a gui slot 32 of player with Lime Dye named "&4&l:| &c&lMETIER DE BRI &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lB.R.I actuel &f&l-> &a&l%{bri.number}%" and "  " and "&aEtat &f&l> &a&lActif" and "" and "&7Clic gauche pour désactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.bri.etat} to "false"
					remove 1 from {jobs.vip.etat.dispo}
					add 1 to {jobs.vip.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de B.R.I a été &d&lDésactivé."
					stop
			else:
				make a gui slot 32 of player with Pink Dye named "&4&l:| &c&lMETIER DE BRI &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lB.R.I actuel &f&l-> &a&l%{bri.number}%" and "  " and "&aEtat &f&l> &d&lDesactivé" and "" and "&7Clic gauche pour réactiver" and "  " and "&c&l-----------" and "&cATTENTION :" and "&cDésactivé &f&l= &cMETIER NON REJOINGNABLE" and "&cActif &f&l= &cMETIER REJOINGNABLE" and "&c&l-----------" to run:
					set {jobs.bri.etat} to "true"
					add 1 to {jobs.vip.etat.dispo}
					remove 1 from {jobs.vip.etat.indispo}
					close player's inventory
					broadcast "&4&l>> &cInfo &4&l<< &e- &cLe métier de B.R.I a été &d&lRéactivé."
					stop
			make a gui slot 33 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 34 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 35 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 36 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 37 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 38 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 39 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 40 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 41 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 42 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 43 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 44 of player with Red Stained Glass Pane named "&4Quitter" to close
			stop
		make a gui slot 12 of player with blaze powder named "&d&l:| &6&lWarps &d&l|" to run:
			wait 3 tick
			open chest inventory with 6 rows named "   " to player
			make a gui slot 0 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 1 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 2 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 3 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 4 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 5 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 6 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 7 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 8 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 9 of player with White Stained Glass Pane named "&cPrisonRP" to close 
			make a gui slot 10 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Prison" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1234, 7, 1269, world("world"), 0, 0)	
			make a gui slot 11 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Rebelle" and "  " and "&6&l>> &e&l------------------" and "  " to run:				
				teleport player to location(-1260, 12, 1033, world("world"), 0, 0)	

			make a gui slot 12 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Parcelle" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1358, 4, 918, world("world"), 91.6, 2.7)			
			make a gui slot 13 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur de Parcelle" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1323, 5, 925, world("world"), -90.5, 4.1)


			make a gui slot 14 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Traiteur 1" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1389, 4, 1024, world("world"), -48.2, 6.6)	
			make a gui slot 15 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Traiteur 2" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1317, 8, 1177, world("world"), 45.7, 10.2)		
			make a gui slot 16 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Traiteur 3" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1266, 12, 1270, world("world"), 89.4, 4.7)
			make a gui slot 17 of player with White Stained Glass Pane named "&cPrisonRP" to close	
			make a gui slot 18 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 19 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur de munition Prison" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1271, 12, 1284, world("world"), 120, 2)	
			make a gui slot 20 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur de munition Extérieur" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1367, 8, 1203, world("world"), 0.8, 6)			
			make a gui slot 21 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur de Protection" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1407, 4, 1199, world("world"), -90.3, 7.1)		
			make a gui slot 22 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Manoir" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1400, 9, 1126, world("world"), 91.4, 1.7)	
			make a gui slot 23 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur de Pioche" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1260, 5, 1286, world("world"), 3.2, 5.3)		
			make a gui slot 24 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Traiteur d'argent salle" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1258, 9, 1271, world("world"), -171.8, 5.6)
			make a gui slot 25 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur de décoration" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1321, 9, 943, world("world"), -90.1, 6)	
			make a gui slot 26 of player with White Stained Glass Pane named "&cPrisonRP" to close	
			make a gui slot 27 of player with White Stained Glass Pane named "&cPrisonRP" to close		
			make a gui slot 28 of player with barrier named "&cPrisonRP" to close
			make a gui slot 29 of player with barrier named "&cPrisonRP" to close	
			make a gui slot 30 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Cuisinier Extérieur" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1362, 4, 1187, world("world"), -89.6, 4.4)			
			make a gui slot 31 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Cuisinier Intérieur" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1261, 12, 1261, world("world"), -128, 5.6)		
			make a gui slot 32 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Fournisseur de bombe en Prison" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1271, 8, 1231, world("world"), -34.2, 7.4)	
			make a gui slot 33 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Fournisseur de bombe extérieur" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1263, 12, 1034, world("world"), -178.5, 3.9)		
			make a gui slot 34 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur de Printer" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1260, 8, 1032, world("world"), -177.7, 5.6)
			make a gui slot 35 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 36 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 37 of player with cauldron named "&6-&c-&6-&c-&6=&c=&e&lTéléportation&c=&6=&c-&6-&c-&6-" with lore "  " and "&cWarps:" and "&9Vendeur d'armes" and "  " and "&6&l>> &e&l------------------" and "  " to run:										
				teleport player to location(-1262, 4, 1036, world("world"), 1.4, 17.1)	
			make a gui slot 38 of player with barrier named "&cPrisonRP" to close
			make a gui slot 39 of player with barrier named "&cPrisonRP" to close
			make a gui slot 40 of player with barrier named "&cPrisonRP" to close
			make a gui slot 41 of player with barrier named "&cPrisonRP" to close
			make a gui slot 42 of player with barrier named "&cPrisonRP" to close
			make a gui slot 43 of player with barrier named "&cPrisonRP" to close	
			make a gui slot 44 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 45 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 46 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 47 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 48 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 49 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 50 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 51 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 52 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 53 of player with Red Stained Glass Pane named "&4Quitter" to close	
			stop
		make a gui slot 18 of player with Red Stained Glass Pane named "&4Quitter" to close
		make a gui slot 13 of player with White Stained Glass Pane named "&4Quitter" to close
		make a gui slot 14 of player with block of redstone named "&d&l:| &d&lStatut du Serveur &d&l|" to run:
			wait 3 tick
			open chest inventory with 3 rows named "&d&l:| &d&lStatut du Serveur &d&l|" to player
			make a gui slot 0 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 1 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 2 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 3 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 4 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 5 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 6 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 7 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 8 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 9 of player with White Glass Pane named "&cPrisonRP" to close
			make a gui slot 10 of player with White Glass Pane named "&cPrisonRP" to close
			if {statut.maintenance} isn't "true":
				make a gui slot 11 of player with Lime Dye named "&4&l:| &6&lSERVICE DE MAINTENANCE &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lJoueurs connectés &f&l-> &a&l%{Online}% " and "  " and "&aEtat &f&l> &a&lOuvert" and "" and "&7Clic gauche pour activer" to run:
					send "   " to all players
					send "&4&l>> &cInfo &4&l<< &e- &cLe serveur est en maintenance, kick all dans 1 minute." to all players
					send "   " to all players
					close player's inventory
					set {statut.maintenance} to "true"
					wait 1 minutes
					send "   " to all players
					send "&4&l>> &cInfo &4&l<< &e- &cServeur en maintenance." to all players
					send "   " to all players
					kick all players due to "&4&l>> &cInfo &4&l<< &e- &cServeur est actuellement en maintenance !"
					stop
			else:
				make a gui slot 11 of player with Pink Dye named "&4&l:| &6&lSERVICE DE MAINTENANCE &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lJoueurs connectés &f&l-> &a&l%{Online}% " and "  " and "&aEtat &f&l> &c&lEn maintenance" and "" and "&7Clic gauche pour désactiver" to run:
					close player's inventory
					set {statut.maintenance} to "false"
					send "   " to all players
					send "&4&l>> &cInfo &4&l<< &e- &cServeur N'EST PLUS en maintenance." to all players
					send "   " to all players
					stop		
			make a gui slot 12 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 13 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 14 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 15 of player with Lime Dye named "&4&l:| &6&lSTOPPER LE SERVEUR &4&l|:" with lore "  " and "&f&lTous les détails :" and "&a&l> &9&lJoueurs connectés &f&l-> &a&l%{Online}% " and "  " and "&aEtat &f&l> &a&lOuvert" and "" and "&7Clic gauche pour activer" and "  " to run:
				make console execute command "/stop"
				stop
			make a gui slot 16 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 17 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 18 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 19 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 20 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 21 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 22 of player with Red Stained Glass Pane named "&4Quitter" to close
			make a gui slot 23 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 24 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 25 of player with White Stained Glass Pane named "&cPrisonRP" to close
			make a gui slot 26 of player with Red Stained Glass Pane named "&4Quitter" to close
			stop
		make a gui slot 15 of player with nether star named "&cQuitter le mode Développeur" to run:
			make player execute command "/developpeur"
			stop
		make a gui slot 16 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 17 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 19 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 20 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 21 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 22 of player with Red Stained Glass Pane named "&4Quitter" to close
		make a gui slot 23 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 24 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 25 of player with White Stained Glass Pane named "&cPrisonRP" to close
		make a gui slot 26 of player with Red Stained Glass Pane named "&4Quitter" to close
		stop
		